export const HANDLE_ACCORDION_EXPANDED = 'HANDLE_ACCORDION_EXPANDED'
export const START_BEDTIME = 'START_BEDTIME '
export const SET_PAUSE_TIME = 'SET_PAUSE_TIME'
export const SET_TIME_PAUSED = 'SET_TIME_PAUSED'
export const TOGGLE_BEDTIME_DRAWER = 'TOGGLE_BEDTIME_DRAWER'
export const SET_CURRENT_AUDIO_PLAYING = 'SET_CURRENT_AUDIO_PLAYING'
export const SET_CURRENT_AUDIO_REF = 'SET_CURRENT_AUDIO_REF'

export const SET_DEFAULT_CONFIGURATIONS = 'SET_DEFAULT_CONFIGURATIONS'