export const NIGHT_LIGHT_BRIGHTNESS = 'NIGHT_LIGHT_BRIGHTNESS'
export const NIGHT_TIME_SOUND_VOLUME = 'NIGHT_TIME_SOUND_VOLUME'
export const WAKE_TIME_SOUND_VOLUME = 'WAKE_TIME_SOUND_VOLUME'
export const WAKE_LIGHT_BRIGHTNESS = 'WAKE_LIGHT_BRIGHTNESS'