export const NIGHT_LIGHT_BRIGHTNESS = 'NIGHT_LIGHT_BRIGHTNESS'
export const NIGHT_LIGHT_BRIGHTNESS_LEVEL = 'NIGHT_LIGHT_BRIGHTNESS_LEVEL'

export const NIGHT_TIME_SOUND_VOLUME = 'NIGHT_TIME_SOUND_VOLUME'
export const NIGHT_TIME_SOUND_VOLUME_LEVEL = 'NIGHT_TIME_SOUND_VOLUME_LEVEL'

export const WAKE_TIME_SOUND_VOLUME = 'WAKE_TIME_SOUND_VOLUME'
export const WAKE_TIME_SOUND_VOLUME_LEVEL = 'WAKE_TIME_SOUND_VOLUME_LEVEL'

export const WAKE_LIGHT_BRIGHTNESS = 'WAKE_LIGHT_BRIGHTNESS'
export const WAKE_LIGHT_BRIGHTNESS_LEVEL = 'WAKE_LIGHT_BRIGHTNESS_LEVEL'