export const NIGHT_LIGHT_BRIGHTNESS = 'NIGHT_LIGHT_BRIGHTNESS'
export const NIGHT_LIGHT_BRIGHTNESS_LEVEL = 'NIGHT_LIGHT_BRIGHTNESS_LEVEL'

export const NIGHT_TIME_AUDIO = 'NIGHT_TIME_AUDIO'
export const NIGHT_TIME_SOUND_VOLUME = 'NIGHT_TIME_SOUND_VOLUME'
export const NIGHT_TIME_SOUND_VOLUME_LEVEL = 'NIGHT_TIME_SOUND_VOLUME_LEVEL'

export const WAKE_TIME_AUDIO = 'WAKE_TIME_AUDIO'
export const WAKE_TIME_SOUND_VOLUME = 'WAKE_TIME_SOUND_VOLUME'
export const WAKE_TIME_SOUND_VOLUME_LEVEL = 'WAKE_TIME_SOUND_VOLUME_LEVEL'

export const WAKE_LIGHT_BRIGHTNESS = 'WAKE_LIGHT_BRIGHTNESS'
export const WAKE_LIGHT_BRIGHTNESS_LEVEL = 'WAKE_LIGHT_BRIGHTNESS_LEVEL'

export const SELECT_WAKE_TIME_SOUND = 'SELECT_WAKE_TIME_SOUND'
export const TOGGLE_SOUND_SELECTOR = 'TOGGLE_SOUND_SELECTOR'

export const BEDTIME_SOUND = 'BEDTIME_SOUND'
export const NIGHT_LIGHT_STATUS = 'NIGHT_LIGHT_STATUS'
export const WAKE_LIGHT_STATUS = 'WAKE_LIGHT_STATUS'

export const WAKE_TIME = 'WAKE_TIME'

export const RESET_TO_DEFAULT = 'RESET_TO_DEFAULT'

