on:
  push:
    branches: [ dev-node-red ]
  pull_request:
    branches: [ dev-node-red ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
    - run: cd ~/.node-red/uibuilder
    - run: ls
    - run: whoami
    # - run: # git pull. app should be managed with pm2 to watch for changes and restart.
    # - run: npm run build